server:
  port: 8764
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: zks123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: userservice
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: GZHU

mybatis:
  type-aliases-package: com.gzhu.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

